### Create room

POST http://localhost:3050/api/v1/room/new

### Register

POST http://localhost:3050/api/v1/room/61fdf9dc6e9ccd41d886a1e1/register
Content-Type: application/json

{
  "name": "Dima"
}
