### Create room

POST http://localhost:3050/api/v1/room/new

### Register

POST http://localhost:3050/api/v1/room/61fdee08918b4a099079a71e/register
Content-Type: application/json

{
  "name": "Dima"
}
