### Create room

POST http://localhost:3050/api/v1/room/new

### Register

POST http://localhost:3050/api/v1/room/61fe25651cee5f2f1b2fd33a/register
Content-Type: application/json

{
  "name": "Player2"
}

### Start game

POST http://localhost:3050/api/v1/room/61fe25651cee5f2f1b2fd33a/start
Content-Type: application/json

{
  "token": "iJ9rd9"
}

### Room status

POST http://localhost:3050/api/v1/room/61fe25651cee5f2f1b2fd33a/status
Content-Type: application/json

{
  "playerId": "61fe25a71cee5f2f1b2fd33c",
  "token": "ME9wPw"
}

### Answer

POST http://localhost:3050/api/v1/room/61fe25651cee5f2f1b2fd33a/answer
Content-Type: application/json

{
  "playerId": "61fe25a71cee5f2f1b2fd33c",
  "token": "ME9wPw",
  "answer": "3987"
}

### Get story

POST http://localhost:3050/api/v1/room/61fe25651cee5f2f1b2fd33a/story
Content-Type: application/json

{
  "playerId": "61fe25a71cee5f2f1b2fd33c",
  "token": "ME9wPw"
}
